spring.application.name=Hospital-ERP

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_erp
spring.datasource.username=root
spring.datasource.password=Root@1628

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080